
apiVersion: greenhouse.sap/v1alpha1
kind: Plugin
metadata:
  name: ceph-operations-st1-qa-de-1
  namespace: ccloud
spec:
  pluginDefinition: ceph-operations
  displayName: Ceph operations bundle
  clusterName: st1-qa-de-1
  disabled: false
  optionValues: []
  releaseNamespace: rook-ceph